### ISSUE TITLE
Game (Pt. 1 - Setup Logic)

### ISSUE THREAD

**Issue by aadiego** [aadiego/CollegeProjects#15]
### Tasks
- [x] Set Outbreak to 0 (Max 8) and Infection Rate to 2 (2,2,2,3,3,4,4)
- [x] Instance all the cities (#11) and add a research station to Atlanta
- [x] Populate and shuffle Infection Deck
- [x] Infect 9 Cities - 3 cities with an infection value of 3, 3 cities with an infection value of 2, 3 cities with an infection value of 1
- [x] Populate city cards and shuffle Player Deck
- [x] Draw 5 cards and store in Player Hand
- [x] Divide Player Deck into 4 equal piles
- [x] Create 4 epidemic cards and one per pile.
- [x] Shuffle individual piles and combined into one Player Deck

**Comment by aadiego** [comment]
Code has been commented.
