### ISSUE TITLE
Game (Pt. 2 - Player Turn Logic) / Role and Player Class

### ISSUE THREAD

**Issue by aadiego** [aadiego/CollegeProjects#16]
#### Actions (up to 4 actions)
- [x] Drive / Ferry
- [x] Direct Flight
- [x] Charter Flight
- [x] Shuttle Flight
- [x] Build a Research Station
- [x] Treat Disease
- [x] Discover a Cure
- [x] Pass

#### End Turn
- [x] Draw 2 cars from the Player Deck (resolve any Epidemics #17 )

BasePlayer
----|
\- name : string<br>\- maxActions : unsigned int<br>\- playerHand : Stack<PlayerCard><br>\- maxCardsInHand : unsigned int = 9<br>\- playerLocation : City* = nullptr<br>\- discoverCureNumber : unsigned int = 5
\+ BasePlayer(name : string, startingLocation : City*, maxActions : unsigned int = 4, discoverCureNumber : unsigned int = 5, maxCardsInHand : unsigned int = 9) : <br>\+ ~BasePlayer() : = default<br>\+ getName() const : string<br>\+ getMaxActions() const : unsigned int<br>\+ getMaxCardsInHand() const : unsigned int<br>\+ getPlayerHandCards() : vector<PlayerCard\*><br>\+ getPlayerLocation() : City*<br>\+ AddPlayerCardToHand(card : PlayerCard) : void<br>\+ DiscardCardFromHand(card : PlayerCard\*) : void<br>\+ isPlayerHandAtMax() : bool<br>\+ getAvailableActions() : vector<string><br>\+ DriveFerry() : virtual bool<br>\+ CharterFlight() : virtual bool<br>\+ ShuttleFlight() : virtual bool<br>\+ BuildResearchStation() : virtual bool<br>\+ TreatDisease(IsMedic : bool = false) : virtual bool<br>\+ DiscoverCure() : virtual bool<br>\- calcDiscoverCureCards() const : vector\<vector\<PlayerCard\>\>

MedicRole : public BasePlayer
----|
\- roleName : string<br>\- description : string
\+ MedicRole(name : string, startingCity : City\*) : <br>\+ ~MedicRole() : = default<br>\+ getRoleName : string<br>\+ getDescription() : string<br>\- ClearCuredInfections() : void<br>\+ DriveFerry() override : bool<br>\+ DirectFlight() override : bool<br>\+ CharterFlight() override : bool<br>\+ ShuttleFlight() override : bool<br>\+ TreatDisease(IsMedic : bool = false) override : bool

**Comment by aadiego** [comment]
Original Design Plan:

### Tasks
#### Actions (up to 4 actions)
- [x] Drive / Ferry
- [x] Direct Flight
- [x] Charter Flight
- [x] Shuttle Flight
- [x] Build a Research Station
- [x] Treat Disease
- [x] Discover a Cure
- [x] Pass

#### End Turn
- [x] Draw 2 cars from the Player Deck (resolve any Epidemics #17 )

Role
----|
\- roleName : string<br>\- description : string<br>\- maxActions : uint
\+ Role(name : string, description : string, maxActions : uint = 4) : <br>\+ getAvailableActions() : string []<br>\+ getRoleName() : string<br>\+ getDescription() : string<br>\+ DriveFerry() : void<br>\+ CharterFlight(city : Card*) : void<br>\+ ShuttleFlight(city : Card*) : void<br>\+ BuildResearchStation(city : Card*) : void<br>\+ TreatDisease() : void<br>\+ DiscoverCure(disease : Disease*, cards : Cards*[]) : void<br>\+ Pass() : void|

Player : public Role
----|
\- playerName : string<br>\- location : City*|
\+ Player(name : string) : <br>\+ getName : string<br>\+ getLocation() : City*<br>\+ _override inherited Action functions_|

**Comment by aadiego** [comment]
UML Diagram updated and code commented.
