### ISSUE TITLE
Game (Pt. 3 - Game Turn Logic)

### ISSUE THREAD

**Issue by aadiego** [aadiego/CollegeProjects#17]
### Tasks
- [x] Resolve any Epidemic cards
- [x] Draw Infection Deck card and resolve by adding 1 infection value to the city

#### Epidemics
- [x] Increase Infection Rate
- [x] Draw bottom card of Infection Deck and add an infection value of 3 to the city. Discard.
- [x] Shuffle discard pile
- [x] Replace on top of the draw pile

#### Outbreaks
- [x] Increase the outbreak count
- [x] Infect neighboring cities with 1 infection value of the disease color (repeat if necessary)

#### Winning / Losing the Game
- [x] Win if all the diseases are cured
- [x] Lose if Player Deck runs out, outbreaks = 8, infections of one disease > max value

**Comment by aadiego** [comment]
Code has been commented.
